[package]
name = "ria_lv2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2 = { version = "0.6.0", features = ["full"] }
serde_json = "1.0.59"
serde = { version = "1.0.136", features = ["derive"] }
biquad = "0.4.2"
fs2 = "0.4.3"